### ISSUE TITLE
Enable for all markdown files in a PR

### ISSUE THREAD

**Issue by RichardLitt** [dkhamsing/awesome_bot#77]
Would be great to not limit this to README.md, but any markdown files in a PR.

**Comment by dkhamsing** [comment]
@RichardLitt uh you could support multiple files now, just add another line in the ci config (.travis.yml)

```yml
#...
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md 
  - awesome_bot plans.md
# etc   
```
